# import streamlit as st
# import requests
# import datetime

# # from exception.exceptions import TradingBotException
# import sys

# BASE_URL = "http://localhost:8000"  # Backend endpoint

# st.set_page_config(
#     page_title="🌍 Travel Planner Agentic Application",
#     page_icon="🌍",
#     layout="centered",
#     initial_sidebar_state="expanded",
# )

# st.title("🌍 Travel Planner Agentic Application")

# # Initialize chat history
# if "messages" not in st.session_state:
#     st.session_state.messages = []

# # Display chat history
# st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

# # Chat input box at bottom
# with st.form(key="query_form", clear_on_submit=True):
#     user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
#     submit_button = st.form_submit_button("Send")

# if submit_button and user_input.strip():
#     try:
#         # # Show user message
#         # Show thinking spinner while backend processes
#         with st.spinner("Bot is thinking..."):
#             payload = {"question": user_input}
#             response = requests.post(f"{BASE_URL}/query", json=payload)

#         if response.status_code == 200:
#             answer = response.json().get("answer", "No answer returned.")
#             markdown_content = f"""# 🌍 AI Travel Plan

#             # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
#             # **Created by:** Atriyo's Travel Agent

#             ---

#             {answer}

#             ---

#             *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
#             """
#             st.markdown(markdown_content)
#         else:
#             st.error(" Bot failed to respond: " + response.text)

#     except Exception as e:
#         raise Exception(f"The response failed due to {e}")

import streamlit as st
import requests
import datetime

BASE_URL = "http://localhost:8000"  # FastAPI backend URL

# Page configuration
st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

# Title
st.title("🌍 Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Header
st.header(
    "How can I help you in planning a trip? "
    "Let me know where you want to visit."
)

# Input form
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input(
        "User Input",
        placeholder="e.g. Plan a trip to Goa for 5 days"
    )
    submit_button = st.form_submit_button("Send")

# Process request
if submit_button and user_input.strip():
    try:
        with st.spinner("🤖 Bot is thinking..."):
            payload = {"question": user_input}

            response = requests.post(
                f"{BASE_URL}/query",
                json=payload,
                timeout=60  # timeout after 60 seconds
            )

        # Debug information
        st.write("Status Code:", response.status_code)

        if response.status_code == 200:
            try:
                response_data = response.json()
                answer = response_data.get(
                    "answer",
                    "No answer returned."
                )
            except Exception:
                st.error("Backend did not return valid JSON.")
                st.text(response.text)
                st.stop()

            markdown_content = f"""
# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}

**Created by:** Atriyo's Travel Agent

---

{answer}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """

            st.markdown(markdown_content)

        else:
            st.error(
                f"❌ Bot failed to respond "
                f"(Status Code: {response.status_code})"
            )
            st.text(response.text)

    except requests.exceptions.ConnectionError:
        st.error(
            "❌ Cannot connect to the backend server.\n\n"
            "Make sure your FastAPI server is running on "
            "http://localhost:8000"
        )

    except requests.exceptions.Timeout:
        st.error(
            "❌ Request timed out. "
            "The backend took too long to respond."
        )

    except requests.exceptions.RequestException as e:
        st.error(f"❌ Request error: {e}")

    except Exception as e:
        st.error("❌ An unexpected error occurred.")
        st.exception(e)